import React, { useCallback, useEffect, useState } from 'react';
import {
  AlertTriangle,
  Briefcase,
  Building2,
  Calendar,
  CheckCircle2,
  Copy,
  Cpu,
  ExternalLink,
  FileText,
  MapPin,
  Sparkles,
  Wallet,
  X,
  XCircle,
} from 'lucide-react';
import type { JobPost, MatchResult, ResumeProfile, TailorResult } from '../types/job';
import { analyzeMatch, generateCoverLetter, scoreBand, tailorResume } from '../services/aiService';
import { SourceBadge } from './SourceBadge';

/**
 * The Application Kit — everything needed to apply well, prepared up front.
 *
 * This replaces a panel that opened the listing in a new tab and logged the
 * application, while displaying a fixed "Strong Match" label whatever the
 * score was.
 *
 * It deliberately stops short of submitting anything. Auto-filling and
 * submitting third-party ATS forms breaks those portals' terms of service, so
 * the kit prepares the materials and the person presses submit — LoopCV's
 * "review-first" mode, which is the half of their product that does not carry
 * that exposure.
 */

interface ApplicationKitModalProps {
  isOpen: boolean;
  job: JobPost | null;
  activeResume: ResumeProfile | null;
  isApplied: boolean;
  onClose: () => void;
  onTrackApplication: (job: JobPost, coverNote: string, matchScore: number | null) => Promise<void>;
}

type Tab = 'match' | 'resume' | 'letter';

const Panel: React.FC<{ children: React.ReactNode; className?: string }> = ({ children, className = '' }) => (
  <div className={`bg-slate-950/60 border border-slate-800 rounded-xl p-4 ${className}`}>{children}</div>
);

const MethodNote: React.FC<{ method: 'ai' | 'heuristic' | 'template' }> = ({ method }) => (
  <span className="inline-flex items-center gap-1 text-[11px] text-slate-500">
    {method === 'ai' ? (
      <>
        <Sparkles className="w-3 h-3 text-indigo-400" />
        Generated by the configured AI model
      </>
    ) : (
      <>
        <Cpu className="w-3 h-3 text-slate-400" />
        Produced locally without AI — no model is configured
      </>
    )}
  </span>
);

export const ApplicationKitModal: React.FC<ApplicationKitModalProps> = ({
  isOpen,
  job,
  activeResume,
  isApplied,
  onClose,
  onTrackApplication,
}) => {
  const [tab, setTab] = useState<Tab>('match');
  const [match, setMatch] = useState<MatchResult | null>(null);
  const [tailored, setTailored] = useState<TailorResult | null>(null);
  const [letter, setLetter] = useState<{ content: string; method: string } | null>(null);

  const [loading, setLoading] = useState(false);
  const [busySection, setBusySection] = useState<Tab | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [tracked, setTracked] = useState(false);

  // Reset whenever a different job is opened, so nothing from the previous
  // job can be shown against this one.
  useEffect(() => {
    setTab('match');
    setMatch(null);
    setTailored(null);
    setLetter(null);
    setError(null);
    setTracked(false);
  }, [job?.id]);

  useEffect(() => {
    if (!isOpen || !job || !activeResume) return;

    let cancelled = false;
    setLoading(true);
    setError(null);

    analyzeMatch(activeResume, job)
      .then(result => {
        if (!cancelled) setMatch(result);
      })
      .catch(err => {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Could not evaluate this job.');
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [isOpen, job, activeResume]);

  const loadTailored = useCallback(async () => {
    if (!job || !activeResume || tailored) return;
    setBusySection('resume');
    setError(null);
    try {
      setTailored(await tailorResume(activeResume, job));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not tailor the resume.');
    } finally {
      setBusySection(null);
    }
  }, [job, activeResume, tailored]);

  const loadLetter = useCallback(async () => {
    if (!job || !activeResume || letter) return;
    setBusySection('letter');
    setError(null);
    try {
      setLetter(await generateCoverLetter(activeResume, job));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not generate a cover note.');
    } finally {
      setBusySection(null);
    }
  }, [job, activeResume, letter]);

  if (!isOpen || !job) return null;

  const selectTab = (next: Tab) => {
    setTab(next);
    if (next === 'resume') void loadTailored();
    if (next === 'letter') void loadLetter();
  };

  const handleApply = async () => {
    window.open(job.applyUrl, '_blank', 'noopener,noreferrer');
    try {
      await onTrackApplication(job, letter?.content || '', match?.score ?? null);
      setTracked(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Opened the listing, but could not track it.');
    }
  };

  const band = match ? scoreBand(match.score) : null;

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/60 backdrop-blur-sm animate-fadeIn">
      <div className="w-full md:w-[640px] bg-slate-900 h-full shadow-2xl flex flex-col border-l border-slate-800">

        {/* Header */}
        <div className="flex items-start justify-between p-6 border-b border-slate-800/60">
          <div className="space-y-2 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <SourceBadge source={job.platform} allSources={job.sources} />
              <span className="text-xs text-slate-500 flex items-center gap-1">
                <Calendar className="w-3 h-3" />
                {job.postedTime}
              </span>
            </div>
            <h2 className="text-xl font-bold text-slate-100 truncate">{job.title}</h2>
            <div className="flex items-center gap-4 text-sm text-slate-400 flex-wrap">
              <span className="flex items-center gap-1.5">
                <Building2 className="w-4 h-4" />
                {job.company}
              </span>
              <span className="flex items-center gap-1.5">
                <MapPin className="w-4 h-4" />
                {job.location}
              </span>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-full hover:bg-slate-800 text-slate-400 hover:text-white transition-colors shrink-0"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* No resume: the kit cannot be built, and inventing one is what the
            old fallback resume did. */}
        {!activeResume ? (
          <div className="flex-1 flex items-center justify-center p-8">
            <div className="text-center space-y-3 max-w-sm">
              <FileText className="w-10 h-10 text-slate-600 mx-auto" />
              <h3 className="text-sm font-bold text-slate-200">No resume uploaded yet</h3>
              <p className="text-xs text-slate-400">
                Upload a resume in the Resume Vault and this job will be scored against it.
                Nothing can be matched or tailored without one.
              </p>
              <a
                href={job.applyUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold"
              >
                Open the listing anyway <ExternalLink className="w-3.5 h-3.5" />
              </a>
            </div>
          </div>
        ) : (
          <>
            {/* Tabs */}
            <div className="flex items-center gap-1 px-6 pt-4 border-b border-slate-800/60">
              {([
                ['match', 'Match'],
                ['resume', 'Tailored resume'],
                ['letter', 'Cover note'],
              ] as [Tab, string][]).map(([key, label]) => (
                <button
                  key={key}
                  onClick={() => selectTab(key)}
                  className={`px-4 py-2 text-xs font-semibold rounded-t-lg transition-all border-b-2 ${
                    tab === key
                      ? 'border-cyan-400 text-cyan-300'
                      : 'border-transparent text-slate-500 hover:text-slate-300'
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>

            <div className="flex-1 overflow-y-auto p-6 space-y-5">
              {error && (
                <div className="flex items-start gap-2 p-3 rounded-xl bg-rose-500/10 border border-rose-500/30 text-xs text-rose-300">
                  <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
                  {error}
                </div>
              )}

              {tab === 'match' && (
                <div className="space-y-5">
                  {loading && (
                    <Panel className="animate-pulse text-sm text-slate-500">Evaluating this job…</Panel>
                  )}

                  {match && band && (
                    <>
                      <div className={`rounded-xl p-4 border ${band.tone.bg} ${band.tone.border}`}>
                        <div className="flex items-center justify-between gap-3">
                          <h3 className={`text-base font-bold ${band.tone.text}`}>
                            {band.label} — {match.score}%
                          </h3>
                          <MethodNote method={match.method} />
                        </div>
                        <p className="text-xs text-slate-300 mt-2">{match.summary}</p>
                        {match.confidence === 'low' || match.confidence === 'none' ? (
                          <p className="text-[11px] text-amber-400/90 mt-2 flex items-center gap-1.5">
                            <AlertTriangle className="w-3 h-3" />
                            Low confidence — this posting gave little to assess against.
                          </p>
                        ) : null}
                      </div>

                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <Panel>
                          <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            You have ({match.matchedSkills.length})
                          </h4>
                          <div className="flex flex-wrap gap-1.5">
                            {match.matchedSkills.length ? (
                              match.matchedSkills.map(skill => (
                                <span key={skill} className="text-[11px] px-2 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/25 text-emerald-300 font-mono">
                                  {skill}
                                </span>
                              ))
                            ) : (
                              <span className="text-[11px] text-slate-500">Nothing overlapped.</span>
                            )}
                          </div>
                        </Panel>

                        <Panel>
                          <h4 className="text-xs font-bold text-amber-400 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                            <XCircle className="w-3.5 h-3.5" />
                            Gaps ({match.missingSkills.length})
                          </h4>
                          <div className="flex flex-wrap gap-1.5">
                            {match.missingSkills.length ? (
                              match.missingSkills.map(skill => (
                                <span key={skill} className="text-[11px] px-2 py-0.5 rounded bg-slate-900 border border-slate-700 text-slate-400 font-mono">
                                  {skill}
                                </span>
                              ))
                            ) : (
                              <span className="text-[11px] text-slate-500">None — you cover every listed requirement.</span>
                            )}
                          </div>
                        </Panel>
                      </div>

                      {match.recommendations.length > 0 && (
                        <Panel>
                          <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
                            Before you apply
                          </h4>
                          <ul className="space-y-1.5">
                            {match.recommendations.map((rec, i) => (
                              <li key={i} className="text-xs text-slate-300 flex gap-2">
                                <span className="text-cyan-400">•</span>
                                {rec}
                              </li>
                            ))}
                          </ul>
                        </Panel>
                      )}

                      {match.reason && (
                        <details className="text-xs text-slate-500">
                          <summary className="cursor-pointer hover:text-slate-300">
                            How this score was calculated
                          </summary>
                          <p className="mt-2 text-slate-400 leading-relaxed">{match.reason}</p>
                        </details>
                      )}
                    </>
                  )}

                  <div className="flex items-center gap-6 border-t border-slate-800/60 pt-4 text-sm text-slate-300">
                    <span className="flex items-center gap-2">
                      <Briefcase className="w-4 h-4 text-slate-500" />
                      {job.experienceRequired}
                    </span>
                    <span className="flex items-center gap-2">
                      <Wallet className="w-4 h-4 text-slate-500" />
                      {job.salary}
                    </span>
                  </div>

                  <div className="space-y-2">
                    <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider">
                      Job description
                    </h4>
                    <div className="text-sm text-slate-300 whitespace-pre-wrap leading-relaxed">
                      {job.description}
                    </div>
                  </div>
                </div>
              )}

              {tab === 'resume' && (
                <div className="space-y-4">
                  {busySection === 'resume' && (
                    <Panel className="animate-pulse text-sm text-slate-500">Tailoring your resume…</Panel>
                  )}

                  {tailored && (
                    <>
                      <div className="flex justify-end">
                        <MethodNote method={tailored.method} />
                      </div>

                      <Panel>
                        <div className="flex items-center justify-between mb-2">
                          <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">
                            Summary rewritten for this role
                          </h4>
                          <button
                            onClick={() => navigator.clipboard.writeText(tailored.tailoredSummary)}
                            className="flex items-center gap-1 text-[11px] text-slate-400 hover:text-cyan-300"
                          >
                            <Copy className="w-3 h-3" /> Copy
                          </button>
                        </div>
                        <p className="text-sm text-slate-200 leading-relaxed">{tailored.tailoredSummary}</p>
                      </Panel>

                      <Panel>
                        <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
                          Lead with these, in this order
                        </h4>
                        <div className="flex flex-wrap gap-1.5">
                          {tailored.prioritizedSkills.map((skill, i) => (
                            <span
                              key={skill}
                              className={`text-[11px] px-2 py-0.5 rounded font-mono border ${
                                i < 5
                                  ? 'bg-cyan-500/10 border-cyan-500/30 text-cyan-300'
                                  : 'bg-slate-900 border-slate-800 text-slate-500'
                              }`}
                            >
                              {skill}
                            </span>
                          ))}
                        </div>
                      </Panel>

                      {tailored.keywordsToAdd.length > 0 && (
                        <Panel>
                          <h4 className="text-xs font-bold text-amber-400 uppercase tracking-wider mb-1">
                            Terms this posting uses that your resume does not
                          </h4>
                          <p className="text-[11px] text-slate-500 mb-2">
                            Add only the ones that are genuinely true of you.
                          </p>
                          <div className="flex flex-wrap gap-1.5">
                            {tailored.keywordsToAdd.map(keyword => (
                              <span key={keyword} className="text-[11px] px-2 py-0.5 rounded bg-amber-500/10 border border-amber-500/25 text-amber-300 font-mono">
                                {keyword}
                              </span>
                            ))}
                          </div>
                        </Panel>
                      )}

                      {tailored.bulletSuggestions.length > 0 && (
                        <Panel>
                          <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
                            Suggested bullets
                          </h4>
                          <ul className="space-y-2">
                            {tailored.bulletSuggestions.map((bullet, i) => (
                              <li key={i} className="text-xs text-slate-300 flex gap-2">
                                <span className="text-cyan-400">•</span>
                                {bullet}
                              </li>
                            ))}
                          </ul>
                        </Panel>
                      )}
                    </>
                  )}
                </div>
              )}

              {tab === 'letter' && (
                <div className="space-y-4">
                  {busySection === 'letter' && (
                    <Panel className="animate-pulse text-sm text-slate-500">Writing a cover note…</Panel>
                  )}

                  {letter && (
                    <>
                      <div className="flex items-center justify-between">
                        <MethodNote method={letter.method as 'ai' | 'heuristic'} />
                        <button
                          onClick={() => navigator.clipboard.writeText(letter.content)}
                          className="flex items-center gap-1 text-[11px] text-slate-400 hover:text-cyan-300"
                        >
                          <Copy className="w-3 h-3" /> Copy
                        </button>
                      </div>
                      <Panel>
                        <p className="text-sm text-slate-200 whitespace-pre-wrap leading-relaxed">
                          {letter.content}
                        </p>
                      </Panel>
                      <p className="text-[11px] text-slate-500">
                        Read it before sending — check every claim is one you can stand behind.
                      </p>
                    </>
                  )}
                </div>
              )}
            </div>

            {/* Footer action */}
            <div className="p-5 border-t border-slate-800 bg-slate-950/80 space-y-2">
              <button
                onClick={handleApply}
                disabled={!job.applyUrl}
                className="w-full flex items-center justify-center gap-2 py-3 px-4 bg-blue-600 hover:bg-blue-500 disabled:opacity-40 disabled:cursor-not-allowed text-white rounded-xl font-bold transition-all"
              >
                {tracked || isApplied ? (
                  <>
                    <CheckCircle2 className="w-4 h-4" /> Tracked — open listing again
                  </>
                ) : (
                  <>
                    Open listing and track <ExternalLink className="w-4 h-4" />
                  </>
                )}
              </button>
              <p className="text-[11px] text-slate-500 text-center">
                Opens the real posting so you submit it yourself. This app does not
                fill in or submit employer forms on your behalf.
              </p>
            </div>
          </>
        )}
      </div>
    </div>
  );
};
