import { useState } from 'react';
import { Building2, ExternalLink, MapPin, Save, Send, BriefcaseBusiness, CalendarDays } from 'lucide-react';
import type { ApplicationStatus, JobPost, ResumeProfile } from '../types/job';
interface Props { isOpen: boolean; job: JobPost | null; activeResume: ResumeProfile | null; isApplied: boolean; onClose: () => void; onTrackApplication: (job: JobPost, coverNote: string, matchScore: number | null, status?: ApplicationStatus) => Promise<void>; }
export function ApplicationKitModal({isOpen,job,activeResume: _activeResume,isApplied: _isApplied,onClose,onTrackApplication}: Props) {
 const [confirmApply,setConfirmApply]=useState(false); const [notes,setNotes]=useState(''); const [busy,setBusy]=useState(false);
 if (!isOpen || !job) return null;
 const track=async(status:ApplicationStatus)=>{setBusy(true);try{await onTrackApplication(job,notes,job.match?.score??null,status)}finally{setBusy(false)}};
 const apply=async()=>{await track('APPLIED');if(job.applyUrl)window.open(job.applyUrl,'_blank','noopener,noreferrer');setConfirmApply(false)};
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4"><section className="mx-auto my-6 w-full max-w-4xl rounded-xl bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b bg-white p-6"><div><h2 className="text-2xl font-bold text-gray-900">{job.title}</h2><p className="mt-1 flex items-center gap-2 text-gray-700"><Building2 className="h-4 w-4"/>{job.company}</p><div className="mt-2 flex flex-wrap gap-3 text-sm text-gray-600"><span className="flex items-center gap-1"><MapPin className="h-4 w-4"/>{job.location}</span><span className="flex items-center gap-1"><CalendarDays className="h-4 w-4"/>{job.postedAt?`Posted ${job.postedTime}`:'Posted date unavailable'}</span><span className="flex items-center gap-1"><BriefcaseBusiness className="h-4 w-4"/>{job.experienceRequired}</span></div></div><button onClick={onClose} className="rounded border px-3 py-1 text-sm">Close</button></header><div className="space-y-6 p-6">
   <div className="grid gap-3 sm:grid-cols-2"><section className="rounded-lg bg-gray-50 p-4"><h3 className="font-semibold">Job Overview</h3><dl className="mt-3 grid grid-cols-2 gap-y-2 text-sm"><dt>Experience</dt><dd>{job.experienceRequired}</dd><dt>Employment</dt><dd>{job.employmentType ?? 'Not specified'}</dd><dt>Work mode</dt><dd>{job.isRemote?'Remote':'Not specified'}</dd><dt>Salary</dt><dd>{job.salary==='Not disclosed'?'Salary information not provided':job.salary}</dd><dt>Source</dt><dd>{job.platform}</dd></dl></section><section className="rounded-lg bg-gray-50 p-4"><h3 className="font-semibold">Resume Match</h3>{job.match?<><p className="mt-2 text-3xl font-bold text-blue-600">{job.match.score}%</p><p className="mt-2 text-sm">Matched: {job.match.matchedSkills.join(', ')||'None identified'}</p><p className="mt-1 text-sm text-gray-600">Recommended: {job.match.missingSkills.join(', ')||'None'}</p></>:<p className="mt-2 text-sm text-gray-600">Upload or select a resume to calculate your match score.</p>}</section></div>
   {job.skillsRequired.length>0&&<section><h3 className="font-semibold">Required Skills</h3><div className="mt-2 flex flex-wrap gap-2">{job.skillsRequired.map(skill=><span key={skill} className="rounded-full border border-blue-200 bg-blue-50 px-3 py-1 text-sm text-blue-800">{skill}</span>)}</div></section>}
   <section><h3 className="font-semibold">About This Role</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-gray-700">{job.description}</p></section>
   <section className="rounded-lg border p-4"><h3 className="font-semibold">Job Source</h3><p className="mt-2 text-sm">Source: {job.platform}</p>{job.sourceJobId&&<p className="text-sm">Original Job ID: {job.sourceJobId}</p>}{job.applyUrl&&<a className="mt-2 inline-flex items-center gap-1 text-sm text-blue-600" href={job.applyUrl} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4"/>Open original job</a>}</section>
   <label className="block text-sm font-medium">Application notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 w-full rounded border p-2" rows={3} placeholder="Optional notes"/></label>
   <div className="flex flex-wrap gap-3"><button disabled={busy} onClick={()=>void track('SAVED')} className="rounded border px-4 py-2 text-sm font-semibold"><Save className="mr-1 inline h-4 w-4"/>Save Job</button><button disabled={busy} onClick={()=>void track('APPLIED')} className="rounded border px-4 py-2 text-sm font-semibold">Mark as Applied</button><button disabled={busy||!job.applyUrl} onClick={()=>setConfirmApply(true)} className="rounded bg-blue-600 px-4 py-2 text-sm font-semibold text-white"><Send className="mr-1 inline h-4 w-4"/>Apply Now</button></div>
  </div></section>{confirmApply&&<div className="fixed inset-0 z-20 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6"><h3 className="font-bold">Continue to application?</h3><p className="mt-2 text-sm text-gray-600">You are leaving JobPulse to apply on the original job portal.</p><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setConfirmApply(false)} className="rounded border px-3 py-2">Cancel</button><button onClick={()=>void apply()} className="rounded bg-blue-600 px-3 py-2 text-white">Continue to Application</button></div></div></div>}</div>;
}
