import { useEffect, useMemo, useState } from 'react';
import { Search, SlidersHorizontal, Wifi } from 'lucide-react';
import type { JobPost } from '../types/job';
import { JobCard } from './JobCard';
import { createMcpServer, listMcpServers, searchMcp, testMcpServer, type McpServer, type McpTransport } from '../services/mcpService';

type PostedPreset = 'any' | 'today' | 'day' | '3days' | 'week' | 'month' | 'year' | 'custom';
type ExperiencePreset = 'any' | 'fresher' | '0-1' | '1-3' | '3-5' | '5-8' | '8+' | 'custom';
const RANGE: Record<Exclude<ExperiencePreset, 'any' | 'custom'>, [number, number | undefined]> = { fresher:[0,0], '0-1':[0,1], '1-3':[1,3], '3-5':[3,5], '5-8':[5,8], '8+':[8,undefined] };
const ago = (days:number) => { const d=new Date();d.setDate(d.getDate()-days);return d.toISOString().slice(0,10); };

export function McpServerPanel({onOpenJob}:{onOpenJob:(job:JobPost)=>void}) {
  const [servers,setServers]=useState<McpServer[]>([]),[selected,setSelected]=useState(''),[keywords,setKeywords]=useState(''),[location,setLocation]=useState(''),[remote,setRemote]=useState<'any'|'true'|'false'>('any');
  const [experience,setExperience]=useState<ExperiencePreset>('any'),[minExperience,setMinExperience]=useState(''),[maxExperience,setMaxExperience]=useState(''),[posted,setPosted]=useState<PostedPreset>('any'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[limit,setLimit]=useState(25);
  const [sort,setSort]=useState<'best'|'newest'|'oldest'|'experience'|'salary-high'|'salary-low'>('best'),[jobs,setJobs]=useState<JobPost[]>([]),[states,setStates]=useState<Record<string,{status:string;result_count:number;source?:string}>>({}),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);
  const [name,setName]=useState(''),[transport,setTransport]=useState<McpTransport>('streamable-http'),[endpoint,setEndpoint]=useState(''),[saving,setSaving]=useState(false);
  const load=async()=>{try{const rows=await listMcpServers();setServers(rows);setSelected(current=>current||rows[0]?.id||'')}catch{setMessage('MCP server configuration is unavailable.')}};
  useEffect(()=>{void load()},[]);
  const range = experience==='any'?[undefined,undefined]:experience==='custom'?[minExperience?Number(minExperience):undefined,maxExperience?Number(maxExperience):undefined]:RANGE[experience];
  const dateFilters=()=> { if(posted==='custom')return {posted_after:from||undefined,posted_before:to||undefined}; const days=posted==='today'?0:posted==='day'?1:posted==='3days'?3:posted==='week'?7:posted==='month'?30:posted==='year'?365:undefined;return {posted_after:days===undefined?undefined:ago(days)}; };
  const ordered=useMemo(()=>[...jobs].sort((a,b)=>sort==='newest'?(a.postedAt||'').localeCompare(b.postedAt||'')*-1:sort==='oldest'?(a.postedAt||'').localeCompare(b.postedAt||''):sort==='experience'?(a.experienceMin??-1)-(b.experienceMin??-1):sort==='salary-high'?Number(b.salary.replace(/\D/g,''))-Number(a.salary.replace(/\D/g,'')):sort==='salary-low'?Number(a.salary.replace(/\D/g,''))-Number(b.salary.replace(/\D/g,'')):(b.match?.score??-1)-(a.match?.score??-1)),[jobs,sort]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!selected||!keywords.trim())return;setLoading(true);setMessage('');setStates({});try{const response=await searchMcp([selected],keywords.split(',').map(v=>v.trim()).filter(Boolean),location||undefined,remote==='any'?undefined:remote==='true',{experience_min:range[0],experience_max:range[1],...dateFilters(),limit});setJobs(response.results);setStates(response.servers);if(!response.results.length)setMessage('No jobs matched these filters. Listings without an explicit experience or posted date are excluded when that filter is active.')}catch{setMessage('The selected MCP server could not complete this search.')}finally{setLoading(false)}};
  const saveServer=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const server=await createMcpServer({name,transport,endpoint});setServers(rows=>[...rows,server]);setSelected(server.id);setName('');setEndpoint('');setMessage('MCP server saved. Test its connection before searching.')}catch{setMessage('Could not save the MCP server.')}finally{setSaving(false)}};
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-blue-600">MCP Server Integration</p><h2 className="text-2xl font-bold">Search Jobs</h2><p className="text-sm text-gray-600">Deterministic search and filtering from configured job MCP servers.</p></div>{message&&<p className="rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{message}</p>}
    <form onSubmit={submit} className="rounded-xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><SlidersHorizontal className="h-5 w-5 text-blue-600"/><h3 className="font-semibold">Search jobs</h3></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
      <label className="text-sm font-medium">Keywords<input required value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="DevOps Engineer" className="mt-1 w-full rounded border p-2"/></label><label className="text-sm font-medium">Location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Chennai" className="mt-1 w-full rounded border p-2"/></label><label className="text-sm font-medium">Job Source / MCP<select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-1 w-full rounded border p-2">{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      <label className="text-sm font-medium">Experience<select value={experience} onChange={e=>setExperience(e.target.value as ExperiencePreset)} className="mt-1 w-full rounded border p-2"><option value="any">Any Experience</option><option value="fresher">Fresher / 0 years</option><option value="0-1">0–1 years</option><option value="1-3">1–3 years</option><option value="3-5">3–5 years</option><option value="5-8">5–8 years</option><option value="8+">8+ years</option><option value="custom">Custom range</option></select></label><label className="text-sm font-medium">Posted Date<select value={posted} onChange={e=>setPosted(e.target.value as PostedPreset)} className="mt-1 w-full rounded border p-2"><option value="any">Any Time</option><option value="today">Today</option><option value="day">Last 24 Hours</option><option value="3days">Last 3 Days</option><option value="week">Last 7 Days</option><option value="month">Last 30 Days</option><option value="year">This Year</option><option value="custom">Custom Date Range</option></select></label><label className="text-sm font-medium">Remote<select value={remote} onChange={e=>setRemote(e.target.value as typeof remote)} className="mt-1 w-full rounded border p-2"><option value="any">Any</option><option value="true">Remote</option><option value="false">On-site / Hybrid</option></select></label>
      {experience==='custom'&&<div className="flex gap-2"><label className="text-sm font-medium">Minimum Experience<input type="number" min="0" value={minExperience} onChange={e=>setMinExperience(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm font-medium">Maximum Experience<input type="number" min="0" value={maxExperience} onChange={e=>setMaxExperience(e.target.value)} className="mt-1 w-full rounded border p-2"/></label></div>}{posted==='custom'&&<div className="flex gap-2"><label className="text-sm font-medium">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm font-medium">To<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 w-full rounded border p-2"/></label></div>}<label className="text-sm font-medium">Results per page<select value={limit} onChange={e=>setLimit(Number(e.target.value))} className="mt-1 w-full rounded border p-2"><option>25</option><option>50</option><option>100</option></select></label>
    </div><button disabled={loading||!selected} className="mt-5 rounded bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Search className="mr-2 inline h-4 w-4"/>{loading?'Searching jobs…':'Search Jobs'}</button></form>
    {!!Object.keys(states).length&&<div className="rounded-xl border bg-white p-4"><h3 className="mb-2 text-sm font-semibold">Source status</h3>{Object.entries(states).map(([id,state])=><p key={id} className="text-sm text-gray-600">{servers.find(s=>s.id===id)?.name ?? id}: <span className={state.status==='success'?'text-emerald-700':'text-red-700'}>{state.status==='success'?`${state.result_count} jobs found`:'Unable to retrieve jobs'}</span></p>)}</div>}
    {jobs.length>0&&<div className="flex items-center justify-between"><p className="font-semibold">{jobs.length} jobs found</p><label className="text-sm">Sort by <select value={sort} onChange={e=>setSort(e.target.value as typeof sort)} className="ml-2 rounded border p-2"><option value="best">Best Match</option><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="experience">Experience</option><option value="salary-high">Salary: High → Low</option><option value="salary-low">Salary: Low → High</option></select></label></div>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{ordered.map(job=><JobCard key={job.id} job={job} activeResume={null} isApplied={false} onOpen={onOpenJob}/>)}</div>
    <details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-semibold">Configure an MCP server</summary><form onSubmit={saveServer} className="mt-4 grid gap-4 md:grid-cols-2"><label>Name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label>Transport<select value={transport} onChange={e=>setTransport(e.target.value as McpTransport)} className="mt-1 w-full rounded border p-2"><option value="streamable-http">Streamable HTTP</option><option value="sse">SSE</option><option value="stdio">Standard input/output</option></select></label><label className="md:col-span-2">Server URL / Command<input required value={endpoint} onChange={e=>setEndpoint(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><button disabled={saving} className="rounded bg-gray-800 p-2 text-white">{saving?'Saving…':'Save MCP Server'}</button></form>{servers.map(s=><div className="mt-3 flex items-center justify-between text-sm" key={s.id}><span>{s.name} · {s.transport}</span><button type="button" className="text-blue-600" onClick={()=>void testMcpServer(s.id).then(load)}>Test connection <Wifi className="inline h-3 w-3"/></button></div>)}</details>
  </div>;
}
